name: Validate flake and build targets
# From astralbijection
# https://github.com/astralbijection/infra/blob/60f3d692e8c694d48adddaac9b8295c9754e686e/.github/workflows/nix-flake-check.yml

on:
  push: {}
  pull_request: {}
  workflow_call: {}

jobs:
  flake-check:
    name: Check Flake
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Validate Nix Flake
        run: GC_DONT_GC=1 nix flake check
  home-manager-build:
    # See https://nix-community.github.io/home-manager/index.html#sec-install-standalone
    name: Build Home Manager configurations
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    
    needs:
      - flake-check
    
    strategy:
      fail-fast: false
      matrix:
        target:
          - autumnal@neesama
          - frie_sv@ft-ssy-sfnb
          - autumnal@index
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Home Manager expression
        shell: nix shell -p home-manager
        run: |
          export GC_DONT_GC=1
          home-manager build --flake '.#${{ matrix.target }}'

  nixos-build:
    # See https://nix-community.github.io/home-manager/index.html#sec-install-standalone
    name: Build NixOS configurations
    runs-on: ubuntu-latest
    
    needs:
      - flake-check
    
    strategy:
      fail-fast: false
      matrix:
        target:
          - index
          - tenshi
    steps:
      - uses: actions/checkout@v2

      - name: Build NixOS expression
        shell: nix shell -p nix
        run: |
          export GC_DONT_GC=1
          nix build .#nixosConfigurations.${{ matrix.target }}.config.system.build.toplevel
